import {
  Bank,
  BankTransaction,
  Customer,
  Vendor,
  VendorTransaction,
  Product,
  StockMovement,
  Invoice,
  PaymentReceipt,
  OfficeExpense,
  Project,
  ProjectExpense,
} from './types';

export const initialBanks: Bank[] = [
  {
    id: 1,
    bank_name: 'Meezan Bank Ltd (Corporate)',
    account_no: '0102-0104882910',
    branch: 'Main Commercial Branch, Blue Area',
    holder_name: 'TRENDZ INTERIOR',
    open_date: '2023-01-15',
    opening_balance: 750000.0,
  },
  {
    id: 2,
    bank_name: 'Habib Bank Limited (HBL Operational)',
    account_no: '2294-7901844921',
    branch: 'Industrial Estate Branch',
    holder_name: 'TRENDZ INTERIOR',
    open_date: '2023-03-10',
    opening_balance: 420000.0,
  },
  {
    id: 3,
    bank_name: 'Standard Chartered Bank',
    account_no: '01-4492019-01',
    branch: 'Civic Centre Executive Branch',
    holder_name: 'TRENDZ INTERIOR',
    open_date: '2023-06-01',
    opening_balance: 980000.0,
  },
];

export const initialBankTransactions: BankTransaction[] = [
  {
    id: 1,
    bank_id: 1,
    trans_date: '2024-01-05',
    description: 'Client Payment - Luxury Penthouse Interior Fitout',
    debit: 350000.0,
    credit: 0.0,
  },
  {
    id: 2,
    bank_id: 1,
    trans_date: '2024-01-10',
    description: 'Payment to Prime Woodcraft & Veneers (Inv #PW-882)',
    debit: 0.0,
    credit: 180000.0,
  },
  {
    id: 3,
    bank_id: 1,
    trans_date: '2024-01-18',
    description: 'Head Design Studio Rent Payment - Trendz Studio HQ',
    debit: 0.0,
    credit: 95000.0,
  },
  {
    id: 4,
    bank_id: 2,
    trans_date: '2024-01-12',
    description: 'Payment Received for Invoice #INV-2024-001 (Apex Builders)',
    debit: 150000.0,
    credit: 0.0,
  },
  {
    id: 5,
    bank_id: 2,
    trans_date: '2024-01-20',
    description: 'Monthly Design Staff & Site Supervisors Payroll (Jan 2024)',
    debit: 0.0,
    credit: 245000.0,
  },
  {
    id: 6,
    bank_id: 3,
    trans_date: '2024-01-15',
    description: 'Payment Received for Invoice #INV-2024-002 (Zenith Luxury Villas)',
    debit: 531000.0,
    credit: 0.0,
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 1,
    name: 'Apex Builders & Developers Ltd',
    phone: '+92 300 8594210',
    address: 'Plot 42-B, Commercial Avenue, Sector F-7',
    email: 'accounts@apexbuilders.pk',
  },
  {
    id: 2,
    name: 'Al-Haramain Heights Infrastructure',
    phone: '+92 321 4455890',
    address: 'Suite 302, Executive Tower, Blue Area',
    email: 'procurement@alharamain.com',
  },
  {
    id: 3,
    name: 'Zenith Solar & Luxury Estates',
    phone: '+92 333 9102834',
    address: 'Plot 18, Industrial Estate Phase 3',
    email: 'projects@zenithsolar.org',
  },
  {
    id: 4,
    name: 'Grand Horizon Hospitality & Suites',
    phone: '+92 345 6789123',
    address: 'Gateway Corridor 9, Motorway Junction',
    email: 'finance@grandhorizon.pk',
  },
];

export const initialVendors: Vendor[] = [
  {
    id: 1,
    name: 'Tariq Mehmood',
    company_name: 'Prime Woodcraft & Natural Veneers',
    phone: '+92 301 5554123',
    address: 'Timber Market, Sector I-9 Industrial Area',
    email: 'sales@primewoodcraft.pk',
  },
  {
    id: 2,
    name: 'Engr. Kamran Siddiqui',
    company_name: 'Luxe Architectural Lighting & Automation',
    phone: '+92 322 7788990',
    address: 'Shop 14, Hall Road Electric & Light Market',
    email: 'orders@luxelighting.com',
  },
  {
    id: 3,
    name: 'Shahid Farooq',
    company_name: 'Marble & Granite Stones Studio',
    phone: '+92 331 6655443',
    address: 'Depot 9, Ring Road Marble Complex',
    email: 'sales@marblestudio.com',
  },
];

export const initialVendorTransactions: VendorTransaction[] = [
  {
    id: 1,
    vendor_id: 1,
    trans_date: '2024-01-08',
    description: 'Teak Wood Fluted Wall Panels & Ash Wood Veneer (25 Sheets)',
    qty: 25,
    rate: 18500.0,
    discount: 5000.0,
    amount: 457500.0,
    trans_type: 'debit',
  },
  {
    id: 2,
    vendor_id: 1,
    trans_date: '2024-01-15',
    description: 'Bank Payment Transfer Ref #BT-9021',
    qty: 0,
    rate: 0,
    discount: 0,
    amount: 300000.0,
    trans_type: 'credit',
  },
  {
    id: 3,
    vendor_id: 2,
    trans_date: '2024-01-11',
    description: 'Magnetic Architectural Track Lights & 3000K Spotlights',
    qty: 12,
    rate: 14500.0,
    discount: 4000.0,
    amount: 170000.0,
    trans_type: 'debit',
  },
  {
    id: 4,
    vendor_id: 2,
    trans_date: '2024-01-22',
    description: 'Cheque Payment #CHQ-440182',
    qty: 0,
    rate: 0,
    discount: 0,
    amount: 170000.0,
    trans_type: 'credit',
  },
];

export const initialProducts: Product[] = [
  {
    id: 1,
    name: 'Magnetic Track Light Rail System 2-Meter (Matte Black)',
    category: 'Architectural Lighting',
    description: 'Surface mounted low-voltage 48V magnetic track system with modular snap-in fixtures',
    unit: 'pcs',
    purchase_price: 6500.0,
    sale_price: 9800.0,
    current_stock: 35,
    min_stock_level: 10,
    max_stock_level: 100,
    reorder_level: 15,
    location: 'Warehouse A, Rack 3-B',
    supplier_id: 2,
    supplier_name: 'Luxe Architectural Lighting & Automation',
    barcode: '890123456701',
    created_date: '2024-01-01 09:30:00',
    last_updated: '2024-01-20 14:15:00',
  },
  {
    id: 2,
    name: 'Premium Acoustic Fluted Wood Wall Panel (Oak Finish)',
    category: 'Wall Cladding & Woodwork',
    description: 'MDF core with natural white oak wood veneer and sound absorbing felt backing (2400x600mm)',
    unit: 'sheets',
    purchase_price: 12500.0,
    sale_price: 17500.0,
    current_stock: 22,
    min_stock_level: 5,
    max_stock_level: 50,
    reorder_level: 8,
    location: 'Warehouse A, Floor Area 1',
    supplier_id: 1,
    supplier_name: 'Prime Woodcraft & Natural Veneers',
    barcode: '890123456702',
    created_date: '2024-01-01 10:00:00',
    last_updated: '2024-01-18 11:20:00',
  },
  {
    id: 3,
    name: 'Italian Carrara White Porcelain Large Slab (1200x2400mm)',
    category: 'Flooring & Surfaces',
    description: 'Glazed polished porcelain tile slab for feature walls and luxury kitchen islands',
    unit: 'sqm',
    purchase_price: 8500.0,
    sale_price: 13200.0,
    current_stock: 45,
    min_stock_level: 10,
    max_stock_level: 120,
    reorder_level: 15,
    location: 'Warehouse B, Shelf 12',
    supplier_id: 3,
    supplier_name: 'Marble & Granite Stones Studio',
    barcode: '890123456703',
    created_date: '2024-01-02 11:45:00',
    last_updated: '2024-01-22 16:10:00',
  },
  {
    id: 4,
    name: 'Custom Velvet Upholstered Executive Lounge Chair',
    category: 'Bespoke Furniture',
    description: 'Ergonomic high-density foam chair with gold brushed stainless steel base',
    unit: 'pcs',
    purchase_price: 34000.0,
    sale_price: 48000.0,
    current_stock: 6,
    min_stock_level: 2,
    max_stock_level: 20,
    reorder_level: 3,
    location: 'Showroom Floor 2',
    supplier_id: 1,
    supplier_name: 'Prime Woodcraft & Natural Veneers',
    barcode: '890123456704',
    created_date: '2024-01-03 14:00:00',
    last_updated: '2024-01-24 10:00:00',
  },
  {
    id: 5,
    name: 'Smart Ambient LED COB Strip 24V 3000K (50m Reel)',
    category: 'Architectural Lighting',
    description: 'High CRI 95+ seamless linear glow strip for cove and under-cabinet illumination',
    unit: 'reel',
    purchase_price: 14200.0,
    sale_price: 19500.0,
    current_stock: 14,
    min_stock_level: 5,
    max_stock_level: 40,
    reorder_level: 8,
    location: 'Warehouse A, Cabinet 2',
    supplier_id: 2,
    supplier_name: 'Luxe Architectural Lighting & Automation',
    barcode: '890123456705',
    created_date: '2024-01-04 15:30:00',
    last_updated: '2024-01-19 12:00:00',
  },
];

export const initialStockMovements: StockMovement[] = [
  {
    id: 1,
    product_id: 1,
    movement_date: '2024-01-10 10:30',
    movement_type: 'purchase',
    quantity: 25,
    reference_type: 'vendor_purchase',
    previous_stock: 10,
    new_stock: 35,
    notes: 'Purchase order #PO-104 stock intake',
  },
  {
    id: 2,
    product_id: 2,
    movement_date: '2024-01-16 15:45',
    movement_type: 'sale',
    quantity: -8,
    reference_type: 'invoice_sale',
    previous_stock: 30,
    new_stock: 22,
    notes: 'Sold on Invoice #INV-2024-001',
  },
  {
    id: 3,
    product_id: 4,
    movement_date: '2024-01-24 09:15',
    movement_type: 'sale',
    quantity: -4,
    reference_type: 'invoice_sale',
    previous_stock: 10,
    new_stock: 6,
    notes: 'Delivered to Executive Suite interior fitout',
  },
];

export const initialInvoices: Invoice[] = [
  {
    id: 1,
    invoice_no: 'INV-2024-001',
    invoice_date: '2024-01-16',
    customer_name: 'Apex Builders & Developers Ltd',
    customer_phone: '+92 300 8594210',
    customer_address: 'Plot 42-B, Commercial Avenue, Sector F-7',
    subtotal: 210000.0,
    advance_amount: 20000.0,
    tax_deduction: 10000.0,
    total_discount: 10000.0,
    total_tax: 36000.0,
    grand_total: 206000.0,
    paid_amount: 150000.0,
    due_amount: 56000.0,
    status: 'partial',
    notes: 'Penthouse Living Room wall paneling and mood lighting package',
    items: [
      {
        description: 'Premium Acoustic Fluted Wood Wall Panel (Oak Finish)',
        qty: 8,
        rate: 17500.0,
        discount: 4000.0,
        tax: 20000.0,
      },
      {
        description: 'Magnetic Track Light Rail System 2-Meter (Matte Black)',
        qty: 5,
        rate: 9800.0,
        discount: 2000.0,
        tax: 8000.0,
      },
      {
        description: 'Design Installation, Custom Wood Framing & Commissioning',
        qty: 1,
        rate: 21000.0,
        discount: 4000.0,
        tax: 8000.0,
      },
    ],
  },
  {
    id: 2,
    invoice_no: 'INV-2024-002',
    invoice_date: '2024-01-22',
    customer_name: 'Zenith Solar & Luxury Estates',
    customer_phone: '+92 333 9102834',
    customer_address: 'Plot 18, Industrial Estate Phase 3',
    subtotal: 475000.0,
    advance_amount: 0.0,
    tax_deduction: 0.0,
    total_discount: 25000.0,
    total_tax: 81000.0,
    grand_total: 531000.0,
    paid_amount: 531000.0,
    due_amount: 0.0,
    status: 'paid',
    notes: 'Executive Boardroom Turnkey Interior & Smart Lighting',
    items: [
      {
        description: 'Italian Carrara White Porcelain Large Slab (1200x2400mm)',
        qty: 20,
        rate: 13200.0,
        discount: 10000.0,
        tax: 42000.0,
      },
      {
        description: 'Custom Velvet Upholstered Executive Lounge Chair',
        qty: 4,
        rate: 48000.0,
        discount: 10000.0,
        tax: 32000.0,
      },
      {
        description: 'Smart Ambient LED COB Strip 24V 3000K (50m Reel)',
        qty: 1,
        rate: 19000.0,
        discount: 5000.0,
        tax: 7000.0,
      },
    ],
  },
  {
    id: 3,
    invoice_no: 'INV-2024-003',
    invoice_date: '2024-01-26',
    customer_name: 'Grand Horizon Hospitality & Suites',
    customer_phone: '+92 345 6789123',
    customer_address: 'Gateway Corridor 9, Motorway Junction',
    subtotal: 320000.0,
    advance_amount: 50000.0,
    tax_deduction: 15000.0,
    total_discount: 15000.0,
    total_tax: 50000.0,
    grand_total: 290000.0,
    paid_amount: 0.0,
    due_amount: 290000.0,
    status: 'unpaid',
    notes: 'Presidential Suite renovation & bespoke false ceiling grid',
    items: [
      {
        description: 'Magnetic Track Light Rail System 2-Meter (Matte Black)',
        qty: 12,
        rate: 9800.0,
        discount: 5000.0,
        tax: 18000.0,
      },
      {
        description: 'Premium Acoustic Fluted Wood Wall Panel (Oak Finish)',
        qty: 10,
        rate: 17500.0,
        discount: 7000.0,
        tax: 25000.0,
      },
      {
        description: 'Architectural False Ceiling Grid Design & Fitout Services',
        qty: 1,
        rate: 27400.0,
        discount: 3000.0,
        tax: 7000.0,
      },
    ],
  },
];

export const initialPaymentReceipts: PaymentReceipt[] = [
  {
    id: 1,
    receipt_no: 'REC-2024-001',
    receipt_date: '2024-01-18',
    invoice_id: 1,
    invoice_no: 'INV-2024-001',
    customer_name: 'Apex Builders & Developers Ltd',
    customer_phone: '+92 300 8594210',
    customer_address: 'Plot 42-B, Commercial Avenue, Sector F-7',
    amount_received: 150000.0,
    payment_mode: 'Bank Transfer',
    bank_id: 2,
    bank_name: 'Habib Bank Limited (HBL Operational)',
    transaction_ref: 'HBL-FT-9920194',
    received_by: 'Accounts Dept / Trendz Interior',
    project_name: 'Apex Luxury Penthouse Fitout',
    notes: 'Advance installment payment against Invoice #INV-2024-001. Remaining balance Rs. 86,000.',
  },
  {
    id: 2,
    receipt_no: 'REC-2024-002',
    receipt_date: '2024-01-24',
    invoice_id: 2,
    invoice_no: 'INV-2024-002',
    customer_name: 'Zenith Solar & Luxury Estates',
    customer_phone: '+92 333 9102834',
    customer_address: 'Plot 18, Industrial Estate Phase 3',
    amount_received: 531000.0,
    payment_mode: 'Bank Transfer',
    bank_id: 3,
    bank_name: 'Standard Chartered Bank',
    transaction_ref: 'SCB-ONLINE-881290',
    received_by: 'Finance Officer / Trendz Interior',
    project_name: 'Executive Boardroom Turnkey',
    notes: 'Full & final payment settlement for invoice #INV-2024-002. Clearance verified.',
  },
];

// Rich domain data for Office Expenses
export const initialOfficeExpenses: OfficeExpense[] = [
  {
    id: 1,
    expense_date: '2024-01-02',
    category: 'Rent',
    description: 'Monthly Design Studio Rent - 4th Floor Commercial Complex',
    paid_to: 'Blue Area Real Estate Trust',
    payment_method: 'Bank Transfer',
    bank_id: 1,
    bill_no: 'RENT-JAN-2024',
    amount: 110000.0,
    notes: 'Paid via Meezan Bank Cheque #980211',
    created_by: 'Admin / Accounts',
  },
  {
    id: 2,
    expense_date: '2024-01-05',
    category: 'Utilities',
    description: 'Studio Electricity & HVAC Bills - IESCO Commercial Meters',
    paid_to: 'IESCO Electricity Dept',
    payment_method: 'Online Transfer',
    bank_id: 2,
    bill_no: 'IESCO-492019-JAN',
    amount: 38450.0,
    notes: 'Meter reading verified by studio manager',
    created_by: 'Accounts Dept',
  },
  {
    id: 3,
    expense_date: '2024-01-08',
    category: 'Salaries & Wages',
    description: 'Interior Drafters & Design Supervisors Monthly Stipends',
    paid_to: 'Studio Design Staff (4 designers)',
    payment_method: 'Bank Transfer',
    bank_id: 1,
    bill_no: 'PAY-ADMIN-JAN24',
    amount: 145000.0,
    notes: 'Direct bank account transfer',
    created_by: 'HR Manager',
  },
  {
    id: 4,
    expense_date: '2024-01-10',
    category: 'Internet & Tech',
    description: 'High-speed Fiber + 3D Rendering Cloud Workstation & AutoCAD Subscriptions',
    paid_to: 'Nayatel Telecom Pvt Ltd',
    payment_method: 'Credit / Debit Card',
    bank_id: 3,
    bill_no: 'NT-881920-01',
    amount: 16800.0,
    notes: 'Software & fiber cloud bundle renewal',
    created_by: 'IT Department',
  },
  {
    id: 5,
    expense_date: '2024-01-12',
    category: 'Office Supplies',
    description: 'Architectural Tracing Paper Rolls, Pantone Color Swatches & HP Plotter Inks',
    paid_to: 'Al-Madina Stationery & Art Mart',
    payment_method: 'Cash / Petty Cash',
    bill_no: 'CASH-REC-104',
    amount: 12500.0,
    notes: 'Petty cash voucher #PV-081 signed by Studio Head',
    created_by: 'Petty Cash Custodian',
  },
  {
    id: 6,
    expense_date: '2024-01-15',
    category: 'Tea & Pantry',
    description: 'Monthly Client Lounge Pantry Supplies (Espresso Beans, Tea, Cookies, Water Bottles)',
    paid_to: 'Metro Cash & Carry Wholesale',
    payment_method: 'Cash / Petty Cash',
    bill_no: 'MTR-994012',
    amount: 18200.0,
    notes: 'Includes refreshments for client design consultations',
    created_by: 'Admin Assistant',
  },
  {
    id: 7,
    expense_date: '2024-01-18',
    category: 'Maintenance & Repairs',
    description: 'Quarterly Inverter AC Servicing & Lighting Showcase Track Repair',
    paid_to: 'CoolPoint HVAC Services',
    payment_method: 'Cash / Petty Cash',
    bill_no: 'CP-SRV-2024-11',
    amount: 14000.0,
    notes: 'Showroom spotlights & HVAC serviced',
    created_by: 'Facility Caretaker',
  },
  {
    id: 8,
    expense_date: '2024-01-22',
    category: 'Printing & Stationery',
    description: 'Official TRENDZ INTERIOR Catalogues, Material Portfolios & Luxury Bags',
    paid_to: 'Royal Graphic Printers',
    payment_method: 'Cheque',
    bank_id: 2,
    bill_no: 'RGP-INV-551',
    amount: 22000.0,
    notes: '1,000 corporate portfolio brochures printed',
    created_by: 'Marketing Lead',
  },
  {
    id: 9,
    expense_date: '2024-01-25',
    category: 'Miscellaneous',
    description: 'Courier Shipping & Material Sample Logistics to Client Sites',
    paid_to: 'TCS Express Logistics',
    payment_method: 'Cash / Petty Cash',
    bill_no: 'TCS-CN-440192',
    amount: 6800.0,
    notes: 'Sample boards and finishes dispatched',
    created_by: 'Accounts Admin',
  },
];

// Rich domain data for Projects and Project Expenses
export const initialProjects: Project[] = [
  {
    id: 1,
    name: 'Penthouse Suite 14B Luxury Fitout',
    client_name: 'Apex Builders & Developers',
    location: 'Sector F-7 Executive Heights',
    budget: 4500000.0,
    start_date: '2023-11-01',
    status: 'In Progress',
  },
  {
    id: 2,
    name: 'Grand Skyline Commercial Restaurant & Cafe',
    client_name: 'Grand Horizon Hospitality',
    location: 'Jinnah Commercial Blvd',
    budget: 2800000.0,
    start_date: '2023-12-15',
    status: 'In Progress',
  },
  {
    id: 3,
    name: 'Zenith Executive Corporate Boardroom',
    client_name: 'Zenith Solar & Luxury Estates',
    location: 'Chakri Highway Executive Park',
    budget: 3200000.0,
    start_date: '2024-01-05',
    status: 'In Progress',
  },
  {
    id: 4,
    name: 'Boutique Fashion Showroom Interior',
    client_name: 'Al-Haramain Infrastructure',
    location: 'Blue Area Plaza 4',
    budget: 1950000.0,
    start_date: '2024-01-10',
    status: 'Planning',
  },
];

export const initialProjectExpenses: ProjectExpense[] = [
  {
    id: 1,
    project_id: 1,
    project_name: 'Penthouse Suite 14B Luxury Fitout',
    expense_date: '2024-01-04',
    expense_type: 'Raw Materials',
    description: 'Imported Solid Brass Edge Profiles & Moisture Resistant MDF Boards (30 sheets)',
    contractor_supplier: 'Prime Woodcraft & Natural Veneers',
    voucher_no: 'PVCH-PRJ1-001',
    payment_method: 'Bank Transfer',
    bank_id: 1,
    amount: 320000.0,
    notes: 'Delivered directly to Penthouse 14B site with quality inspection stamp',
  },
  {
    id: 2,
    project_id: 1,
    project_name: 'Penthouse Suite 14B Luxury Fitout',
    expense_date: '2024-01-09',
    expense_type: 'Labor & Subcontractors',
    description: 'Master Carpenter Team & Fluted Wall Paneling Specialist Wages (Week 1)',
    contractor_supplier: 'Precision Carpentry Guild',
    voucher_no: 'PVCH-PRJ1-002',
    payment_method: 'Cheque',
    bank_id: 2,
    amount: 145000.0,
    notes: 'Completed living room and dining room feature wall framing',
  },
  {
    id: 3,
    project_id: 1,
    project_name: 'Penthouse Suite 14B Luxury Fitout',
    expense_date: '2024-01-14',
    expense_type: 'Equipment & Machinery',
    description: 'Laser Level Aligners & Precision Mitre Saw Rental (5 Days)',
    contractor_supplier: 'Fast Track Machinery & Tools',
    voucher_no: 'PVCH-PRJ1-003',
    payment_method: 'Bank Transfer',
    bank_id: 1,
    amount: 180000.0,
    notes: 'Equipment tested and operating on site',
  },
  {
    id: 4,
    project_id: 1,
    project_name: 'Penthouse Suite 14B Luxury Fitout',
    expense_date: '2024-01-19',
    expense_type: 'Permits & Compliance',
    description: 'High-Rise Architectural Fitout Approval & Fire Safety Compliance Fee',
    contractor_supplier: 'Building Development Authority',
    voucher_no: 'PVCH-PRJ1-004',
    payment_method: 'Online Transfer',
    bank_id: 3,
    amount: 75000.0,
    notes: 'Building NOC and electrical load clearance verified',
  },
  {
    id: 5,
    project_id: 2,
    project_name: 'Grand Skyline Commercial Restaurant & Cafe',
    expense_date: '2024-01-08',
    expense_type: 'Raw Materials',
    description: 'Custom Terrazzo Floor Tiles & Bar Counter Quartz Top Slabs',
    contractor_supplier: 'Marble & Granite Stones Studio',
    voucher_no: 'PVCH-PRJ2-001',
    payment_method: 'Bank Transfer',
    bank_id: 2,
    amount: 215000.0,
    notes: 'Material approved by Interior Designer',
  },
  {
    id: 6,
    project_id: 2,
    project_name: 'Grand Skyline Commercial Restaurant & Cafe',
    expense_date: '2024-01-15',
    expense_type: 'Labor & Subcontractors',
    description: 'Certified Electricians & Track Lighting Installation Team Wages',
    contractor_supplier: 'Precision MEP Technicians Guild',
    voucher_no: 'PVCH-PRJ2-002',
    payment_method: 'Cash / Petty Cash',
    amount: 92000.0,
    notes: 'Work inspected by Site Project Engineer',
  },
  {
    id: 7,
    project_id: 2,
    project_name: 'Grand Skyline Commercial Restaurant & Cafe',
    expense_date: '2024-01-21',
    expense_type: 'Safety & PPE',
    description: 'Dust Masks, Eye Protection Goggles, Safety Helmets & Scaffolding Nets',
    contractor_supplier: 'Safety First Industrial Gear',
    voucher_no: 'PVCH-PRJ2-003',
    payment_method: 'Cash / Petty Cash',
    amount: 34500.0,
    notes: 'Mandatory PPE for ceiling painting & sanding stage',
  },
  {
    id: 8,
    project_id: 3,
    project_name: 'Zenith Executive Corporate Boardroom',
    expense_date: '2024-01-12',
    expense_type: 'Site Logistics & Fuel',
    description: 'Transportation & Safe Rigging of 12-Seater Acoustic Conference Table',
    contractor_supplier: 'Fast Movers Logistics',
    voucher_no: 'PVCH-PRJ3-001',
    payment_method: 'Bank Transfer',
    bank_id: 1,
    amount: 228000.0,
    notes: 'Safely unloaded to 5th floor boardroom',
  },
  {
    id: 9,
    project_id: 3,
    project_name: 'Zenith Executive Corporate Boardroom',
    expense_date: '2024-01-20',
    expense_type: 'Raw Materials',
    description: 'Acoustic Fabric Wall Panels & Brushed Gold Aluminum Reveal Channels',
    contractor_supplier: 'Prime Woodcraft & Natural Veneers',
    voucher_no: 'PVCH-PRJ3-002',
    payment_method: 'Bank Transfer',
    bank_id: 3,
    amount: 410000.0,
    notes: 'Soundproof NRC 0.85 rating verified',
  },
  {
    id: 10,
    project_id: 3,
    project_name: 'Zenith Executive Corporate Boardroom',
    expense_date: '2024-01-24',
    expense_type: 'Site Overhead',
    description: 'Deep Cleaning, Site Protection Sheeting & Site Security',
    contractor_supplier: 'CleanPro Facilities & Protection',
    voucher_no: 'PVCH-PRJ3-003',
    payment_method: 'Bank Transfer',
    bank_id: 1,
    amount: 68000.0,
    notes: 'Pre-handover polishing and protection',
  },
];
